spring.application.name=server
# Dados de Conexão
spring.datasource.url=jdbc:postgresql://localhost:5432/agendo_db
spring.datasource.username=admin
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Mágica do Hibernate: Cria/Atualiza as tabelas sozinho baseado nas classes Java
spring.jpa.hibernate.ddl-auto=update

# Mostra no console o SQL que o Spring está executando (bom para aprender!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto do Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=admin
spring.security.user.password=admin